---
    - name : "Node app"
      hosts: localhost
      connection: local
      
      
   
      vars:
        homeDir: /home/ubuntu
        appDir: app
        account: CEBS13
        repo: Chat-App-using-Socket.io	

   




      tasks:
       - name: "Install Nodejs"
         apt:
           name:
            - npm
            - git
            - curl
            - nodejs
           state: present
         become: yes
        
       - name: Install pm2
         npm: name=pm2 global=yes production=yes
         become: yes
         
     

       - name: "git clone repo"
         git: 
           repo: git://github.com/{{ account }}/{{ repo }}
           dest: "{{homeDir}}/{{ appDir }}"
         register: git_finished
         become: yes     
      
       - name: Install app depedencies
         npm:
          path: "{{homeDir }}/{{ appDir }}"
         register: npm_finished
         when: git_finished.changed
         become: yes
   
       - name: Delete app.
         command: pm2 delete chat-app
         become: yes
         
         
       - name: Start App.
         command: pm2 start {{homeDir}}/{{appDir}}/app.js --name chat-app
         ignore_errors: yes
         become: yes
         
       - name: Startup script.
         command: "env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu"
         become: yes 
       
       - name: Save app.
         command: pm2 save
         become: yes