---
    - name : "Node app"
      hosts: localhost
      connection: local
      become: yes
      
   
      vars:
        homeDir: /home/ubuntu
        appDir: app
        account: CEBS13
        repo: Chat-App-using-Socket.io	
   
   




      tasks:
       - name: "Install Nodejs"
         apt:
           name:
            - npm
            - git
            - curl
            - nodejs
           state: present
          
        
       - name: Install pm2
         npm: name=pm2 global=yes production=yes
         
         
     

       - name: "git clone repo"
         git: 
           repo: git://github.com/{{ account }}/{{ repo }}
           dest: "{{homeDir}}/{{ appDir }}"
         register: git_finished
        # become_user: ubuntu
        # become_method: sudo
         
         
   
       - name: Install app depedencies
         npm:
          path: "{{homeDir }}/{{ appDir }}"
         register: npm_finished
         when: git_finished.changed
   
       - name: Delete app.
         command: pm2 delete chat-app
         ignore_errors : yes
   
       - name: Start App.
         command: pm2 start {{homeDir}}/{{appDir}}/app.js --name chat-app
         ignore_errors: yes
        
       
       - name: Startup script.
         command: "env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u root --hp /home/ubuntu"
         